### PR TITLE
A simpler gaussian_heuristic in python

### PR DESCRIPTION
**Pull request by lducas**
Also in Sync with the renaming of fplll gaussian_heuristic -> adjust_radius_to_gh_bound

### CODE REVIEW

**Comment by malb** [comment]
Why not put the new function in `util.pyx`? I'm not convinced `algorithms.util` is a good place for this kind of code.

**Comment by lducas** [comment]
Sure, i thought pyx was only for cython, not python...
Le 22 déc. 2016 15:39, "Martin Albrecht" <notifications@github.com> a
écrit :
>
> Why not put the new function in util.pyx? I'm not convinced
algorithms.util is a good place for this kind of code.

**Comment by malb** [comment]
It's a bit of an overkill for Python but nothing prevents us from putting Python code there.

**Comment by lducas** [comment]
Done.

2016-12-22 17:06 GMT+01:00 Martin Albrecht <notifications@github.com>:

**Pull request merged**
