### PR TITLE
Release the GIL earlier

### PR DESCRIPTION
**Pull request by thedrow**
It's better to release the GIL as soon and reacquire it in case of errors.
You'll gain a bit more execution in parallel in the normal case.

### CODE REVIEW

**Comment by thedrow** [comment]
Seems like I have a syntax error there... One moment.

**Comment by thedrow** [comment]
Not sure if I can mix elif with a compile time IF.

**Comment by thedrow** [comment]
@malb Any input on this?
The if statements can be run without the GIL for sure since it's just C code.

**Comment by malb** [comment]
Happy for a PR which releases the GIL early. I'd guess, though, that the actual LLL reduction will take much longer than the Python code, so I'm not sure how much of a difference it would make.

I think you have to separate `IF` and `if` to make it compile.

**Comment by malb** [comment]
Is this PR dead and shall be closed?

**Comment by thedrow** [comment]
Yeh don't really have time to work on this.

**Pull request closed without merging**
