### PR TITLE
Add CVP method support.

### LINKED ISSUE #136: CVPMethod not accessible from fpylll
The `fpylll` interface was not updated when the method argument was added to fplll's CVP solver: https://github.com/fplll/fplll/commit/2793aea35b9f5be3c4e5d6a2396405f4f84956fb

This should be somehow synchronized and updated.

### PR DESCRIPTION
**Pull request by J08nY**
Adds support for specifying the CVP method, also update the fplll interface. Fixes #136 .

### CODE REVIEW

**Comment by J08nY** [comment]
Hmm, it seems that setting the default to `CVPM_PROVED` fails the test, as fplll's default is `CVPM_FAST` even though the SVP default is `SVPM_PROVED`. So the CVP test actually tests the fast method?

**Comment by malb** [comment]
Indeed, looks like `CVPM_FAST` is the default: https://github.com/fplll/fplll/blob/master/fplll/svpcvp.h#L52 However, it is a bit disconcerting that `CVPM_PROVED` and `CVP_FAST` give different answers for this small test.

**Comment by J08nY** [comment]
If the result of that enumeration in the test is indeed correct then `CVPM_PROVED` is the incorrect algo here. Anyway, I think having access to this option from fpylll is a fair feature and this can get merged right?

**Comment by malb** [comment]
I agree, the bug uncovered here is no reason not to merge the PR. For completeness, here's how to reproduce the bug:

```python
from fpylll import *
FPLLL.set_random_seed(6)
A = LLL.reduction(IntegerMatrix.random(40, "uniform", bits=10))
t = list(IntegerMatrix.random(40, "uniform", bits=10)[0])                                                                               

fast = CVP.closest_vector(A, t, method="fast")
proved = CVP.closest_vector(A, t, "proved")

sum((fast[i]-t[i])**2 for i in range(40)) < sum((proved[i]-t[i])**2 for i in range(40))
```

Note that the distance of `fast` is smaller than the distance of `proved`

**Pull request merged**
