### PR TITLE
Fixeval

### PR DESCRIPTION
**Pull request by gbonnoron**
Few fixes:
 - solutions iterator were used in reverse order...
 - access to eval strategy

We should confirm the first point. I will in the train :)

### CODE REVIEW

**Comment by gbonnoron** [comment]
This is good to merge for me!

**Comment by malb** [comment]
- Maybe change `def __init__(self, MatGSO M, nr_solutions=1, strategy=EVALSTRATEGY_BEST_N_SOLUTIONS)` to `def __init__(self, MatGSO M, nr_solutions=1, strategy=EnumerationStrategy.BEST_N_SOLUTIONS)`

- Do we care about `EnumerationStrategy` vs `EvalutationStrategy`, which one is right?

**Comment by gbonnoron** [comment]
That is right. It may not be the best name....
Ok to change the __init__ it indeed makes more consistency

Do you want me to do in fixeval and PR again?

**Comment by malb** [comment]
Already merged, a new PR would be good

**Pull request merged**
