### PR TITLE
Revert "Fix sage path" 

### PR DESCRIPTION
**Pull request by joerowell**
This reverts commit a249d630debd8e96d536c37762f250d562aaec65. This is to address #221 and #133.

### CODE REVIEW

**Comment by malb** [comment]
Do we need to remove this, i.e. does it hurt? It's a nice workaround when the Sage installation was moved? I don't mind having a special case four our "biggest customer" in there.

**Comment by joerowell** [comment]
It doesn't hurt at all (I don't think): as you've mentioned, it should just
be a fallback case for when the installation is moved.

**Comment by dimpase** [comment]
This is a wrong workaround - if there was anything to work around in the 1st place, it's failure to get the correct path full for `default.json`. This is something that is not Sage specific.

**Comment by dimpase** [comment]
In fact I'm not too happy with the fplll fix in https://github.com/fplll/fplll/pull/486 - it's not needed, one should always be able to form the correct path from BKZ.DEFAULT_STRATEGY_PATH and BKZ.DEFAULT_STRATEGY. I don't know in which versions of fplll
these values are as they are in the latest version, i.e.  BKZ.DEFAULT_STRATEGY_PATH is the path, and BKZ.DEFAULT_STRATEGY is just the file name, but it's been the case for some time, no?

I'd rather just fix                
```
kwds["strategies"] = load_strategies_json(BKZ.DEFAULT_STRATEGY)
```
in `src/sage/matrix/matrix_integer_dense.pyx`.

Some distros,e.g. Fedora, seem to have BKZ.DEFAULT_STRATEGY with the full path, not sure if it was old behaviour,or they resorted to patch it...

**Pull request closed without merging**
